// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr20yeKNQJHqKevfLEFKFfZAiMmiFRXbY',
    appId: '1:571502069670:web:81346639a10dbf1e95f167',
    messagingSenderId: '571502069670',
    projectId: 'climateshield-app',
    authDomain: 'climateshield-app.firebaseapp.com',
    storageBucket: 'climateshield-app.firebasestorage.app',
    measurementId: 'G-EG9LG9TKCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbwBiWWxrSlooQ0_H41sKzzuI8Xqv914',
    appId: '1:571502069670:android:9be4ecc4cac5b6ea95f167',
    messagingSenderId: '571502069670',
    projectId: 'climateshield-app',
    storageBucket: 'climateshield-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZNIlOr_CQ854T8_AItbUoYvXvb8_GfY',
    appId: '1:571502069670:ios:520cbf7966d8585995f167',
    messagingSenderId: '571502069670',
    projectId: 'climateshield-app',
    storageBucket: 'climateshield-app.firebasestorage.app',
    iosBundleId: 'com.example.climaShield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZNIlOr_CQ854T8_AItbUoYvXvb8_GfY',
    appId: '1:571502069670:ios:520cbf7966d8585995f167',
    messagingSenderId: '571502069670',
    projectId: 'climateshield-app',
    storageBucket: 'climateshield-app.firebasestorage.app',
    iosBundleId: 'com.example.climaShield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr20yeKNQJHqKevfLEFKFfZAiMmiFRXbY',
    appId: '1:571502069670:web:07cbb95f8483e52795f167',
    messagingSenderId: '571502069670',
    projectId: 'climateshield-app',
    authDomain: 'climateshield-app.firebaseapp.com',
    storageBucket: 'climateshield-app.firebasestorage.app',
    measurementId: 'G-HMRKR0YQ3Y',
  );
}
